/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author Aron
 */
public class main extends javax.swing.JFrame {
 public static LinkedList correos =new LinkedList();
 public static String emai;
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Bienbenido = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        contraseña = new javax.swing.JPasswordField();
        arroba = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        siguiente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bienbenido.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        Bienbenido.setForeground(new java.awt.Color(255, 255, 255));
        Bienbenido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user (2).png"))); // NOI18N
        jPanel2.add(Bienbenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 170, 150));

        Email.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(0, 102, 0));
        Email.setText("Email");
        jPanel2.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 70, -1));

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(0, 102, 0));
        password.setText("Password");
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 81, -1));

        contraseña.setBackground(new java.awt.Color(204, 255, 204));
        contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contraseñaMouseClicked(evt);
            }
        });
        jPanel2.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 320, 40));

        arroba.setBackground(new java.awt.Color(0, 255, 0));
        arroba.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        arroba.setForeground(new java.awt.Color(102, 102, 102));
        arroba.setText("@unamba.edu.pe");
        jPanel2.add(arroba, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 190, 50));

        email.setBackground(new java.awt.Color(204, 255, 204));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 150, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/candado.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 40, 50));

        siguiente.setBackground(new java.awt.Color(0, 153, 153));
        siguiente.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        siguiente.setForeground(new java.awt.Color(204, 255, 204));
        siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pequeño.png"))); // NOI18N
        siguiente.setToolTipText("");
        siguiente.setBorder(null);
        siguiente.setBorderPainted(false);
        siguiente.setContentAreaFilled(false);
        siguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        siguiente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pequeño.png"))); // NOI18N
        siguiente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas_pequeño.png"))); // NOI18N
        siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siguienteMouseClicked(evt);
            }
        });
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        jPanel2.add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 80, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/email.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 40, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 500));

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed

    }//GEN-LAST:event_emailActionPerformed

    private void contraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseñaMouseClicked

    }//GEN-LAST:event_contraseñaMouseClicked

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed

    }//GEN-LAST:event_siguienteActionPerformed

    private void siguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siguienteMouseClicked
        int valorASCII=0;
        char caracter;
        boolean band=false;
        String pass =contraseña.getText();
        String usu=email.getText();
        emai=email.getText();
        String usuario="Javier";
        String Contraseña="manzana21";
        for(int i=0;i<usu.length();i++){
            caracter =usu.charAt(i);
            valorASCII= (int) caracter;
            if(valorASCII >=48 && valorASCII <= 57){
                correos.add(usu);
                band=false;
            }
            else{
                band=true;
            }}

            if(band==false){
                if(gestion.comprobar(email.getText())==true){
                    student ventanastudent= new student();
                    ventanastudent.setVisible(true);
                    student.recibe.setText(usu);

                    this.dispose(); }
                else{
                    JOptionPane.showMessageDialog(null, "usted estudiante no esta registrado por el docente");
                }
            }
            if(band==true){
                if(email.getText().equals(usuario)&&pass.equals(Contraseña)){
                    Docente1 ventanaDocente= new Docente1();
                    ventanaDocente.setVisible(true);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "usted esta ingresando como docente"+"\npero no esta registrado en el sistema");
                }}
    }//GEN-LAST:event_siguienteMouseClicked
    public String nombredocen(){
        return contraseña.getText();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienbenido;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel arroba;
    private javax.swing.JPasswordField contraseña;
    public static javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel password;
    private javax.swing.JButton siguiente;
    // End of variables declaration//GEN-END:variables
}
